"""empty message

Revision ID: 703d3157b7d8
Revises: a45ba23f0ab7
Create Date: 2021-04-12 22:26:04.988278

"""

# revision identifiers, used by Alembic.
revision = '703d3157b7d8'
down_revision = 'a45ba23f0ab7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
