"""empty message

Revision ID: a45ba23f0ab7
Revises: ea27960f9a4f
Create Date: 2021-04-12 22:19:26.384015

"""

# revision identifiers, used by Alembic.
revision = 'a45ba23f0ab7'
down_revision = 'ea27960f9a4f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
